### ISSUE TITLE
Stream to Sonos - Errorcode 714

### ISSUE THREAD

**Issue by marc4s** [ugjka/blast#1]
`
blast git:(main) ./blast
----------
DLNA receivers
0: 192.168.158.24 - SYMFONISK Bookshelf
----------
Select the DLNA device:
[0]
----------
Audio sources
0: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_5__sink.monitor
1: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_4__sink.monitor
2: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink.monitor
3: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink.monitor
4: alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__source
5: alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source
6: combined.monitor
7: bluez_sink.2C_FD_B4_86_0C_10.a2dp_sink.monitor
8: blast.monitor
----------
Select the audio source:
[7]
----------
Your LAN ip addresses
0: 192.168.158.48
----------
Select the lan IP address for the stream:
[0]
----------
2023/11/10 07:20:12 starting the stream on port 9000 (configure your firewall if necessary)
2023/11/10 07:20:12 stream URI: http://192.168.158.48:9000/stream
2023/11/10 07:20:12 setting av1transport URI and playing
SOAP fault. Code: s:Client | Explanation: UPnPError | Detail: <UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>714</errorCode></UPnPError>

blast git:(main) sudo ufw status
Status: Inactive
`

is this a bug ?
Error on play_media with UPnP Error 714 received: Illegal MIME-Type

if this is correct I found here you may add .mp3/mime-type:

https://github.com/home-assistant/core/issues/37444

**Comment by ugjka** [comment]
It sends audio/mpeg but i also added audio/mp3 now, you can try it on latest master and report back

**Comment by ugjka** [comment]
no response, closing

**Comment by ugjka** [comment]
for what it is worth i switched the program to use ffmpeg for mp3 encoding because i found Lame to be problematic when working on some other project

**Comment by vitaleg** [comment]
The same problem on latest version.

**Comment by marc4s** [comment]
Yes, same here. still the same error. (sorry for late response, I did not got the mails from github regarding this)

**Comment by marc4s** [comment]
I tried both, the prebuild 0.2.0 amd64 and the repo and build it with go
both the same issue

ffmpeg -version 
ffmpeg version 4.4.4-0ubuntu1~22.04.sav1.1 Copyright (c) 2000-2023 the FFmpeg developers

**Comment by ugjka** [comment]
can you post the output of `blast -debug`

**Comment by ugjka** [comment]
Do Sonos actually support DLNA?

![image](https://github.com/ugjka/blast/assets/13318673/dc411e88-ef23-471e-9770-87470b1e7cc9)

**Comment by ugjka** [comment]
https://en.community.sonos.com/components-and-architectural-228999/still-no-dlna-support-in-sonos-using-jellyfin-6868659

**Comment by vitaleg** [comment]
`----------
DLNA receivers
0: VNet-MediaCenter
1: 192.168.250.24 - Sonos One SL
----------
Select the DLNA device:
[1]
(*goupnp.MaybeRootDevice)(0xc00019e5e8)({
 USN: (string) (len=76) "uuid:RINCON_C438757BF8D201400_MR::urn:schemas-upnp-org:service:AVTransport:1",
 Root: (*goupnp.RootDevice)(0xc000192c00)({
  XMLName: (xml.Name) {
   Space: (string) (len=31) "urn:schemas-upnp-org:device-1-0",
   Local: (string) (len=4) "root"
  },
  SpecVersion: (goupnp.SpecVersion) {
   Major: (int32) 1,
   Minor: (int32) 0
  },
  URLBase: (url.URL) http://192.168.250.24:1400/xml/device_description.xml,
  URLBaseStr: (string) (len=53) "http://192.168.250.24:1400/xml/device_description.xml",
  Device: (goupnp.Device) Device ID uuid:RINCON_C438757BF8D201400 : urn:schemas-upnp-org:device:ZonePlayer:1 (192.168.250.24 - Sonos One SL)
 }),
 Location: (*url.URL)(0xc0001c8510)(http://192.168.250.24:1400/xml/device_description.xml),
 LocalAddr: (net.IP) (len=16 cap=16) 192.168.250.105,
 Err: (error) <nil>
})
([]*av1.AVTransport1) (len=1 cap=1) {
 (*av1.AVTransport1)(0xc0001e2680)({
  ServiceClient: (goupnp.ServiceClient) {
   SOAPClient: (*soap.SOAPClient)(0xc0000000c0)({
    EndpointURL: (url.URL) http://192.168.250.24:1400/MediaRenderer/AVTransport/Control,
    HTTPClient: (http.Client) {
     Transport: (http.RoundTripper) <nil>,
     CheckRedirect: (func(*http.Request, []*http.Request) error) <nil>,
     Jar: (http.CookieJar) <nil>,                                                                                                                                           
     Timeout: (time.Duration) 0s                                                                                                                                            
    }                                                                                                                                                                       
   }),
   RootDevice: (*goupnp.RootDevice)(0xc000082c00)({
    XMLName: (xml.Name) {
     Space: (string) (len=31) "urn:schemas-upnp-org:device-1-0",
     Local: (string) (len=4) "root"
    },
    SpecVersion: (goupnp.SpecVersion) {
     Major: (int32) 1,
     Minor: (int32) 0
    },
    URLBase: (url.URL) http://192.168.250.24:1400/xml/device_description.xml,
    URLBaseStr: (string) (len=53) "http://192.168.250.24:1400/xml/device_description.xml",
    Device: (goupnp.Device) Device ID uuid:RINCON_C438757BF8D201400 : urn:schemas-upnp-org:device:ZonePlayer:1 (192.168.250.24 - Sonos One SL)
   }),
   Location: (*url.URL)(0xc0001c8510)(http://192.168.250.24:1400/xml/device_description.xml),
   Service: (*goupnp.Service)(0xc000147730)(Service ID urn:upnp-org:serviceId:AVTransport : urn:schemas-upnp-org:service:AVTransport:1),
   localAddr: (net.IP) <nil>
  }
 })
}
(interface {}) <nil>
<?xml version="1.0" encoding="utf-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
    <deviceType>urn:schemas-upnp-org:device:ZonePlayer:1</deviceType>
    <friendlyName>192.168.250.24 - Sonos One SL</friendlyName>
    <manufacturer>Sonos, Inc.</manufacturer>
    <manufacturerURL>http://www.sonos.com</manufacturerURL>
    <modelNumber>S38</modelNumber>
    <modelDescription>Sonos One SL</modelDescription>
    <modelName>Sonos One SL</modelName>
    <modelURL>http://www.sonos.com/products/zoneplayers/S38</modelURL>
    <softwareVersion>76.2-47270</softwareVersion>
    <swGen>2</swGen>
    <hardwareVersion>1.28.2.6-2.2</hardwareVersion>
    <serialNum>C4-38-75-7B-F8-D2:1</serialNum>
    <MACAddress>C4:38:75:7B:F8:D2</MACAddress>
    <UDN>uuid:RINCON_C438757BF8D201400</UDN>
    <iconList>
      <icon>
        <id>0</id>
        <mimetype>image/png</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/img/icon-S38.png</url>
      </icon>
    </iconList>
    <minCompatibleVersion>75.0-00000</minCompatibleVersion>
    <legacyCompatibleVersion>58.0-00000</legacyCompatibleVersion>
    <apiVersion>1.37.1</apiVersion>
    <minApiVersion>1.1.0</minApiVersion>
    <displayVersion>15.11</displayVersion>
    <extraVersion></extraVersion>
    <nsVersion>35</nsVersion>
    <roomName>Living Room</roomName>
    <displayName>One SL</displayName>
    <zoneType>40</zoneType>
    <feature1>0x00000000</feature1>
    <feature2>0x01418332</feature2>
    <feature3>0x0541580e</feature3>
    <seriesid>A201</seriesid>
    <variant>2</variant>
    <internalSpeakerSize>5</internalSpeakerSize>
    <memory>512</memory>
    <flash>512</flash>
    <ampOnTime>10</ampOnTime>
    <retailMode>0</retailMode>
    <SSLPort>1443</SSLPort>
    <securehhSSLPort>1843</securehhSSLPort>
    <serviceList>
      <service>
        <serviceType>urn:schemas-upnp-org:service:AlarmClock:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:AlarmClock</serviceId>
        <controlURL>/AlarmClock/Control</controlURL>
        <eventSubURL>/AlarmClock/Event</eventSubURL>
        <SCPDURL>/xml/AlarmClock1.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:MusicServices:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:MusicServices</serviceId>
        <controlURL>/MusicServices/Control</controlURL>
        <eventSubURL>/MusicServices/Event</eventSubURL>
        <SCPDURL>/xml/MusicServices1.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:DeviceProperties:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:DeviceProperties</serviceId>
        <controlURL>/DeviceProperties/Control</controlURL>
        <eventSubURL>/DeviceProperties/Event</eventSubURL>
        <SCPDURL>/xml/DeviceProperties1.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:SystemProperties:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:SystemProperties</serviceId>
        <controlURL>/SystemProperties/Control</controlURL>
        <eventSubURL>/SystemProperties/Event</eventSubURL>
        <SCPDURL>/xml/SystemProperties1.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:ZoneGroupTopology:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:ZoneGroupTopology</serviceId>
        <controlURL>/ZoneGroupTopology/Control</controlURL>
        <eventSubURL>/ZoneGroupTopology/Event</eventSubURL>
        <SCPDURL>/xml/ZoneGroupTopology1.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:GroupManagement:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:GroupManagement</serviceId>
        <controlURL>/GroupManagement/Control</controlURL>
        <eventSubURL>/GroupManagement/Event</eventSubURL>
        <SCPDURL>/xml/GroupManagement1.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:schemas-tencent-com:service:QPlay:1</serviceType>
        <serviceId>urn:tencent-com:serviceId:QPlay</serviceId>
        <controlURL>/QPlay/Control</controlURL>
        <eventSubURL>/QPlay/Event</eventSubURL>
        <SCPDURL>/xml/QPlay1.xml</SCPDURL>
      </service>
    </serviceList>
    <deviceList>
      <device>
  <deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
  <friendlyName>192.168.250.24 - Sonos One SL Media Server</friendlyName>
  <manufacturer>Sonos, Inc.</manufacturer>
  <manufacturerURL>http://www.sonos.com</manufacturerURL>
  <modelNumber>S38</modelNumber>
  <modelDescription>Sonos One SL Media Server</modelDescription>
  <modelName>Sonos One SL</modelName>
  <modelURL>http://www.sonos.com/products/zoneplayers/S38</modelURL>
  <UDN>uuid:RINCON_C438757BF8D201400_MS</UDN>
  <serviceList>
    <service>
      <serviceType>urn:schemas-upnp-org:service:ContentDirectory:1</serviceType>
      <serviceId>urn:upnp-org:serviceId:ContentDirectory</serviceId>
      <controlURL>/MediaServer/ContentDirectory/Control</controlURL>
      <eventSubURL>/MediaServer/ContentDirectory/Event</eventSubURL>
      <SCPDURL>/xml/ContentDirectory1.xml</SCPDURL>
    </service>
    <service>
      <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
            <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
            <controlURL>/MediaServer/ConnectionManager/Control</controlURL>
            <eventSubURL>/MediaServer/ConnectionManager/Event</eventSubURL>
            <SCPDURL>/xml/ConnectionManager1.xml</SCPDURL>
          </service>
        </serviceList>
      </device>
      <device>
        <deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
  <friendlyName>Living Room - Sonos One SL Media Renderer</friendlyName>
  <manufacturer>Sonos, Inc.</manufacturer>
  <manufacturerURL>http://www.sonos.com</manufacturerURL>
  <modelNumber>S38</modelNumber>
  <modelDescription>Sonos One SL Media Renderer</modelDescription>
  <modelName>Sonos One SL</modelName>
  <modelURL>http://www.sonos.com/products/zoneplayers/S38</modelURL>
        <UDN>uuid:RINCON_C438757BF8D201400_MR</UDN>
        <serviceList>
          <service>
            <serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
            <serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
            <controlURL>/MediaRenderer/RenderingControl/Control</controlURL>
            <eventSubURL>/MediaRenderer/RenderingControl/Event</eventSubURL>
            <SCPDURL>/xml/RenderingControl1.xml</SCPDURL>
          </service>
          <service>
            <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
            <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
            <controlURL>/MediaRenderer/ConnectionManager/Control</controlURL>
            <eventSubURL>/MediaRenderer/ConnectionManager/Event</eventSubURL>
            <SCPDURL>/xml/ConnectionManager1.xml</SCPDURL>
          </service>
          <service>
            <serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
            <serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
            <controlURL>/MediaRenderer/AVTransport/Control</controlURL>
            <eventSubURL>/MediaRenderer/AVTransport/Event</eventSubURL>
            <SCPDURL>/xml/AVTransport1.xml</SCPDURL>
          </service>
          <service>
            <serviceType>urn:schemas-sonos-com:service:Queue:1</serviceType>
            <serviceId>urn:sonos-com:serviceId:Queue</serviceId>
            <controlURL>/MediaRenderer/Queue/Control</controlURL>
            <eventSubURL>/MediaRenderer/Queue/Event</eventSubURL>
            <SCPDURL>/xml/Queue1.xml</SCPDURL>
          </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:GroupRenderingControl:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:GroupRenderingControl</serviceId>
        <controlURL>/MediaRenderer/GroupRenderingControl/Control</controlURL>
        <eventSubURL>/MediaRenderer/GroupRenderingControl/Event</eventSubURL>
        <SCPDURL>/xml/GroupRenderingControl1.xml</SCPDURL>
      </service>
      <service>
          <serviceType>urn:schemas-upnp-org:service:VirtualLineIn:1</serviceType>
          <serviceId>urn:upnp-org:serviceId:VirtualLineIn</serviceId>
          <controlURL>/MediaRenderer/VirtualLineIn/Control</controlURL>
          <eventSubURL>/MediaRenderer/VirtualLineIn/Event</eventSubURL>
          <SCPDURL>/xml/VirtualLineIn1.xml</SCPDURL>
      </service>
        </serviceList>
        <X_Rhapsody-Extension xmlns="http://www.real.com/rhapsody/xmlns/upnp-1-0">
          <deviceID>urn:rhapsody-real-com:device-id-1-0:sonos_1:RINCON_C438757BF8D201400</deviceID>
            <deviceCapabilities>
              <interactionPattern type="real-rhapsody-upnp-1-0"/>
            </deviceCapabilities>
        </X_Rhapsody-Extension>
        <qq:X_QPlay_SoftwareCapability xmlns:qq="http://www.tencent.com">QPlay:2</qq:X_QPlay_SoftwareCapability>
        <iconList>
          <icon>
            <mimetype>image/png</mimetype>
            <width>48</width>
            <height>48</height>
            <depth>24</depth>
            <url>/img/icon-S38.png</url>
          </icon>
        </iconList>
      </device>
    </deviceList>
  </device>
</root>`

**Comment by ugjka** [comment]
[blast.zip](https://github.com/ugjka/blast/files/13903117/blast.zip)

Can you try this version that sends flac instead of mp3

**Comment by vitaleg** [comment]
No changes, unfortunately.

[blast.log](https://github.com/ugjka/blast/files/13903224/blast.log)

**Comment by ugjka** [comment]
Ok, the more I read it seems Sonos simply doesn't support DLNA properly even though its devices advertise themselves as such on the LAN

FWIW, here is a version that dumps raw WAV 
[blast.zip](https://github.com/ugjka/blast/files/13903483/blast.zip)

**Comment by vitaleg** [comment]
This version behaves exactly the same way.

I just checked DLNA casting from Jellyfin, everything works there.

**Comment by ugjka** [comment]
Does jellyfin support casting live streams?

**Comment by vitaleg** [comment]
blast is undetectable on my network.

It's probably caused by this:

# curl -v http://192.168.250.105:9000/steam
*   Trying 192.168.250.105:9000...
* Connected to 192.168.250.105 (192.168.250.105) port 9000 (#0)
> GET /steam HTTP/1.1
> Host: 192.168.250.105:9000
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 11 Jan 2024 13:21:40 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 192.168.250.105 left intact


I don't think it's supposed to be like this.

**Comment by ugjka** [comment]
you have a typo in there `steam` => `stream`

**Comment by vitaleg** [comment]
It worked

```
# ./dlna-send https://download.samplelib.com/mp3/sample-15s.mp3
----------
DLNA receivers
0: VNet-MediaCenter
1: 192.168.250.24 - Sonos One SL
----------
Select the DLNA device:
[1]
```

**Comment by ugjka** [comment]
Hmmm... can you send it https://ugjka.net/ircradio (my irc tts radio)

**Comment by ugjka** [comment]
Here is blast that sends all http headers all in lowercase
[blast.zip](https://github.com/ugjka/blast/files/13905956/blast.zip)

**Comment by vitaleg** [comment]
No changes :-(

**Comment by vitaleg** [comment]
I google this solution - https://www.reddit.com/r/homeassistant/comments/101bj1b/home_assistant_sonos_s1s2_streaming_radio_why_do/

And it worked:
```
# ./dlna-send x-rincon-mp3radio://ugjka.net/ircradio
----------
DLNA receivers
0: VNet-MediaCenter
1: 192.168.250.24 - Sonos One SL
----------
Select the DLNA device:
[1]
```

**Comment by vitaleg** [comment]
But it doesn't work without x-rincon-mp3

```
# ./dlna-send radio://ugjka.net/ircradio
----------
DLNA receivers
0: VNet-MediaCenter
1: 192.168.250.24 - Sonos One SL
----------
Select the DLNA device:
[1]
SOAP fault. Code: s:Client | Explanation: UPnPError | Detail: <UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>714</errorCode></UPnPError>
```

**Comment by vitaleg** [comment]
I changed the streamURL, recompiled, now it works.

```
        if streamAddress.To4() != nil {
                streamURL = fmt.Sprintf("x-rincon-mp3radio://%s:%d/stream", streamAddress, STREAMPORT)
        } else {
```

https://i.imgur.com/YjkQsv2.png

**Comment by ugjka** [comment]
Yeah, I'm working on sonos detector function because this will break most non sonos dlna devices i thing

**Comment by ugjka** [comment]
can you check if this works https://github.com/ugjka/blast/files/13907070/blast.zip

**Comment by vitaleg** [comment]
It works now - https://i.imgur.com/hA2GLj8.png

Thanks for fix.

**Comment by ugjka** [comment]
@marc4s can you confirm too?

**Comment by marc4s** [comment]
just made a git pull. still same

2024/01/12 13:21:42 starting the stream on port 9000 (configure your firewall if necessary)
2024/01/12 13:21:42 stream URI: http://192.168.158.29:9000/stream
2024/01/12 13:21:42 setting av1transport URI and playing
SOAP fault. Code: s:Client | Explanation: UPnPError | Detail: <UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>714</errorCode></UPnPError>

**Comment by marc4s** [comment]
ah I see the zip now. this works! GREAT!! Thank You
