### ISSUE TITLE
Feature: Allow streaming specific programs / audio to dlna

### ISSUE THREAD

**Issue by martin-greentrax** [ugjka/blast#10]
I was using pulseaudio-dlna with pavucontrol for some years and was very happy that with blast something actively developed was working out of the box for me too. :+1: 

What I am missing in blast is that I can only direct all audio to my stereo and not select per application or output. For instance with pulseaudio-dlna/pavucontrol I m able to say e.g. music playing via vlc or ncmpcpp should go to my stereo but audio from firefox still via my computer's own speakers.

Would be great if you consider that as a future feature :)

**Comment by ugjka** [comment]
I will investigate this for sure

**Comment by ugjka** [comment]
Oh wait, it is already possible if you choose `blast.monitor` and then you just send the app's output to it

**Comment by martin-greentrax** [comment]
Ah, I wasn't aware of this. Works for me too. Awesome :100: :)
