### ISSUE TITLE
Detect endianess of the dlna device when sending raw lpcm

### ISSUE THREAD

**Issue by ugjka** [ugjka/blast#12]
otherwise there's a high chance of garbled audio with incorrect endianess. See issue #7 

Apparently BubbleUPNP on android does this somehow.

For now you have to set `-bige` flag if your device is big endian

This only seems to matter for lpcm streaming since stuff like wav and flac are little endian by definition

**Comment by parkerlreed** [comment]
I was talking with the BubbleUPnP dev. Apparently L16 implies big endian.

**Comment by ugjka** [comment]
This [app](https://play.google.com/store/apps/details?id=com.waxrain.airplayer2) expects LE, if i send it BE i get white noise.

Perhaps i should create 2 versions of -uselpcm. `-uselpcm` for be and -uselpcmle for LE

**Comment by ugjka** [comment]
With [v0.6.1](https://github.com/ugjka/blast/releases/tag/v0.6.1) big-endian byte order is implied with `-uselpcm`. There is also little-endian version `-uselpcmle` for some non-standard clients.

`-bige` option is removed

**Comment by parkerlreed** [comment]
> I was talking with the BubbleUPnP dev. Apparently L16 implies big endian.
> 
> > No, L16 is always big endian by definition.
> 
> Looking at the UPnP debug there's no obvious signs. BubbleUPnP might just be sending BE to everything for the Audio Cast

I just tried Bubbles Audio Cast to Rygel on Linux and it gives me an invalid media type, so... I really don't think it's doing any smart detection. It just hopes the receiver supports S16BE. Ouch

![Screenshot_20240219_001706_BubbleUPnP](https://github.com/ugjka/blast/assets/841440/2a8c8928-9bb3-4615-afc0-40c409c2c070)
