### ISSUE TITLE
5 seconds latency

### ISSUE THREAD

**Issue by ShinoNia** [ugjka/blast#19]
Hi. I'm trying to find an easy way to stream audio from PC to a Kodi box. Blast is working for me, but there is about 5s of latency in default settings. Is this normal for DLNA or is it something wrong in my setup?
I can provide more info if needed. Thanks in advance.

**Comment by ugjka** [comment]
DLNA receivers generally keep a buffer on their own, in your case it is 5 seconds. If you want a low latency you should look into airplay or something like that
