### ISSUE TITLE
HTTP request crash

### ISSUE THREAD

**Issue by janmasrovira** [ugjka/blast#2]
After I select the LAN ip address I'm getting this error:
```
2024/01/06 08:54:47 starting the stream on port 9000 (configure your firewall if necessary)
2024/01/06 08:54:47 stream URI: http://192.168.1.18:9000/stream
2024/01/06 08:54:47 setting av1transport URI and playing
goupnp: error performing SOAP HTTP request: Post "http://192.168.1.7:49152/upnp/control/rendertransport1": EOF
```

**Comment by ugjka** [comment]
What device is it

**Comment by ugjka** [comment]
Also can you cast to this app on your phone? https://play.google.com/store/apps/details?id=com.waxrain.airplayer2

**Comment by ugjka** [comment]
[blast.zip](https://github.com/ugjka/blast/files/13850016/blast.zip)

can you try this build

**Comment by janmasrovira** [comment]
I tried again on that branch. I'm still getting the same error.

The dlna device is a Wiim Pro.

**Comment by ugjka** [comment]
can you pull the latest commit 7d562bbe9850145ebf01f696ee5991cadfe3172e and try again

**Comment by janmasrovira** [comment]
It no longer crashes, but it does not seem to reach the wiim pro.
Since the crash has been solved feel free to close the issue

**Comment by ugjka** [comment]
when i find time I'll code some debug functionality to inspect your device

**Comment by ugjka** [comment]
OK, I updated the branch. Fetch changes and run blast with -debug flag and post the output here.

**Comment by janmasrovira** [comment]
I tried it again and this time it worked, problem solved

**Comment by ugjka** [comment]
I released a new version that also has 	github.com/huin/goupnp dependency updated to v1.3.0.
